version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: nonstop/permission.sh
      timeout: 30
      runas: ubuntu

  ApplicationStart:
    - location: nonstop/deploy.sh
      timeout: 120
      runas: ubuntu
